// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from "@lezer/lr";
const spec_identifier = {
    __proto__: null,
    gang: 8,
    funk: 42,
    aura: 48,
    fax: 60,
    cap: 62,
    npc: 66,
    me: 70,
    og: 74,
    and: 118,
    or: 120,
    for: 134,
    if: 138,
    else: 140,
    yap: 144,
    bounce: 148,
    spam: 152
};
export const parser = LRParser.deserialize({
    version: 14,
    states: "1jQYQPOOO!jQPO'#CoOOQO'#DU'#DUO!qQPO'#DVOOQO'#DX'#DXO!qQPO'#DWO$jQQO'#DoOOQO'#EU'#EUOOQO'#ES'#ESOOQO'#D{'#D{QYQPOOO$qQPO'#C_O$vQPO'#CpOOQO'#Cy'#CyOOQO'#C|'#C|OOQO'#DO'#DOO${QPO'#DQO%QQPO'#CsO%VQPO'#DpO%[QPO'#DrO!qQPO'#DuO%aQPO'#DwO%hQPO'#DyOOQO,59Z,59ZO%mQPO,59ZO%tQQO,59qO%{QQO,59rOOQO'#D]'#D]OOQO'#De'#DeO!qQPO,59vO!qQPO,59vO!qQPO,59vO!qQPO,59vO!qQPO,5:VO'YQPO'#DmOOQO,5:W,5:WO'aQPO,5:YOOQO,5:Z,5:ZO!qQPO,5:SO!qQPO,5:SOOQO-E7y-E7yOOQO'#Ca'#CaO'fQPO,58yOOQO'#Ci'#CiO'nQPO,59[O'aQPO,59lOOQO'#Cu'#CuO'sQPO,59_O'{QPO,5:[O!qQPO,5:^O(VQQO,5:aO(^QQO,5:cOOQO,5:c,5:cO!qQPO,5:eOOQO1G.u1G.uOOQO1G/]1G/]O)iQQO1G/bO)vQQO1G/bO+UQQO1G/bO+fQQO1G/bO+vQQO1G/qO,TQQO,5:XOOQO,5:X,5:XOOQO'#DT'#DTOOQO1G/t1G/tO-iQQO1G/nO-pQQO1G/nO-wQPO'#CbO-|QPO'#CgOOQO1G.e1G.eO'iQPO1G.eO.UQPO'#ClO.^QPO1G.vOOQO1G/W1G/WOOQO1G.y1G.yO!qQPO1G.yO.cQPO1G/vO.jQQO1G/xOOQO1G/{1G/{OOQO1G/}1G/}O.qQQO1G0PO!qQPO'#EOO.xQPO1G/sOOQO1G/s1G/sOOQO'#Cd'#CdOOQO,58|,58|O'nQPO'#ChOOQO'#D|'#D|O/QQPO,59ROOQO,59R,59ROOQO7+$P7+$POOQO'#Cm'#CmOOQO,59W,59WO/YQPO,59WOOQO7+$b7+$bO/bQQO7+$eO/iQQO7+%bO/pQPO7+%bOYQPO7+%dOYQPO7+%kO/wQQO,5:jOOQO-E7|-E7|OOQO7+%_7+%_O.^QPO,59SOOQO-E7z-E7zOOQO1G.m1G.mO.XQPO'#D}O0RQPO1G.rOOQO1G.r1G.rOOQO<<HP<<HPO0ZQPO<<H|O0bQQO<<H|OYQPO<<H|O0iQPO<<IOOOQO<<IV<<IVOOQO1G.n1G.nOOQO,5:i,5:iOOQO-E7{-E7{OOQO7+$^7+$^O2SQQOAN>hOYQPOAN>hOOQOAN>hAN>hOYQPOAN>jOYQPOG24SOOQOG24SG24SOOQOG24UG24UOOQOLD)nLD)n",
    stateData:
        "2^~O!uOSPOS~OSZOYPO_ROe[OhaOkVOlVOn]Oo]Oq^Os_Ou`O|SO}SO!ebO!gcO!jdO!leO!nfO!wQO~OXgO~PYO_ROkVOlVOn]Oo]Oq^Os_Ou`O|SO}SO!wQO~OVoO_rOjqOvtO}nO!QkO!RkO!SkO!TnO!UoO!VoO!WoO!YlO!ZlO!]vO!^wO~OfuO~P#fO!wyO~O!w{O~Ov}O~O!w!OO~O_!QO~O_!RO~Of!UO~P!qO_!VO~OX!WO~PYO^!XO~P#fO_rOvtOVzafzajza}za!Qza!Rza!Sza!Tza!Uza!Vza!Wza!Yza!Zza!]za!^za^zabza~O^!`O~P!qO!w!aO~OV!eOY!fO~O_!iO~Of!lOj!mO~Of!nOhaO~P!qOf!pO~P#fOf!qO~P#fO_rOvtOV!Oif!Oij!Oi}!Oi!T!Oi!U!Oi!V!Oi!W!Oi!Y!Oi!Z!Oi!]!Oi!^!Oi^!Oib!Oi~O!Q!Oi!R!Oi!S!Oi~P(eO!QkO!RkO!SkO~P(eO_rOvtO}nO!QkO!RkO!SkO!TnOf!Oij!Oi!Y!Oi!Z!Oi!]!Oi!^!Oi^!Oib!Oi~OV!Oi!U!Oi!V!Oi!W!Oi~P*TOVoO!UoO!VoO!WoO~P*TOf!_i^!_ib!_i~P#fO^!uOb!sO~P#fOVoO_rOvtO}nO!QkO!RkO!SkO!TnO!UoO!VoO!WoO!YlO!ZlOf![ij![i!^![i^![ib![i~O!]![i~P,_O!]vO~P,_O!w!vO~OX!{O!w{O~O^#OO!w!}O~OYPO~Of#TO~P!qO^#UO~P#fO^#VO~P#fO^#YOb!sO~OX#]O!w{O~O^#`Ob#^O~Of#aO~P#fOf#bO~P#fO^#dO~P!qO^!rab!ra~P#fO^#jOb#^O~O^#lO~P!qO^#lO~P#fO!h#nOS!fyY!fy_!fye!fyh!fyk!fyl!fyn!fyo!fyq!fys!fyu!fy|!fy}!fy!e!fy!g!fy!j!fy!l!fy!n!fy!s!fy!w!fyX!fy~O^#oO~P#fOP!R~",
    goto: "*Z!yPPP!zP#W#ZP#^PP#a#g#kPP#r#xP$O!zPP$bP$qPPP$tPP$tP$tP$tPP%f$t$t$t%lPP$t&^PPPPPPP&rPP$tPP$t$t'T$t$b!zP!zPP!zP!zP!zP'k'u'{(RPPP(XP(qeWOPYh#U#V#d#l#n#oRzZR!hzR!w!eQ!gzR!|!hT!y!f!zQ|[T!x!f!zQ!j|R#Z!xQ#P!iR#h#^dWOPYh#U#V#d#l#n#oQ#Q!jR#g#ZdWOPYh#U#V#d#l#n#oR!n!QR!Pa!_VOPRTYdehmnopqrvw!Q!R!V!m!n!s#T#U#V#b#d#l#n#oQ!btR!k}!_TOPRTYdehmnopqrvw!Q!R!V!m!n!s#T#U#V#b#d#l#n#oumUi!S!T!Z![!]!^!_!c!d!o!r#R#S#W#c#kopUi!S!T!^!_!c!d!o!r#R#S#W#c#kysUij!S!T!Y!Z![!]!^!_!c!d!o!r#R#S#W#c#kQYOQhPTxYhQ!z!fR#[!zQ#_#PR#i#_Q!t!_R#X!tWXOPYhQ#e#UQ#f#VQ#m#dQ#p#lQ#q#nR#r#ofUOPYh!Q#U#V#d#l#n#oQiRQjTQ!SdQ!TeQ!YmQ!ZnQ![oQ!]pQ!^qQ!_rQ!cvQ!dwQ!o!RQ!r!VQ#R!mQ#S!nQ#W!sQ#c#TR#k#b",
    nodeNames:
        "⚠ LineComment Program ClassDeclaration gang ClassName Superclass < SuperclassName } { ClassBody MethodDeclaration FunctionName ) ( ParamList ParamName , Block FunctionDeclaration funk ; VarDeclaration aura VariableDefinition = Number String Boolean fax cap Null npc ThisExpr me SuperExpr og . PropertyName VariableName ParenthesizedExpr UnaryExpr UnaryOp ! - BinaryExpr MulOp * / % + > >= <= EqOp == != LogicExpr and or AssignExpr CallExpr ArgList GetExpr ExpressionStatement ForStatement for IfStatement if else PrintStatement yap ReturnStatement bounce WhileStatement spam",
    maxTerm: 86,
    nodeProps: [
        ["openedBy", 9, "{", 14, "("],
        ["closedBy", 10, "}", 15, ")"]
    ],
    skippedNodes: [0, 1],
    repeatNodeCount: 4,
    tokenData:
        "'l~RiXY!pYZ!p]^!ppq!pqr#Rrs#`uv#}xy$Syz$Xz{$^{|$c|}$h}!O$m!O!P$r!P!Q$w!Q![%h!]!^&R!^!_&W!_!`&e!`!a&r!c!}'P#R#S'P#T#o'P#o#p'b#q#r'g~!uS!u~XY!pYZ!p]^!ppq!pR#WP|P!_!`#ZQ#`O!ZQ~#cTOr#`rs#rs;'S#`;'S;=`#w<%lO#`~#wOl~~#zP;=`<%l#`~$SO!S~~$XO_~~$^O^~~$cO!Q~~$hO!T~~$mOb~~$rO}~~$wOv~~$|P!R~!P!Q%P~%USP~OY%PZ;'S%P;'S;=`%b<%lO%P~%eP;=`<%l%P~%mQk~!O!P%s!Q![%h~%vP!Q![%y~&OPk~!Q![%y~&WOf~~&]PV~!_!`&`~&eO!W~~&jPj~!_!`&m~&rO!Y~~&wP!U~!_!`&z~'PO!V~~'US!w~!Q!['P!c!}'P#R#S'P#T#o'P~'gOY~~'lOX~",
    tokenizers: [0, 1],
    topRules: { Program: [0, 2] },
    specialized: [
        { term: 85, get: (value: string) => spec_identifier[value as "__proto__"] || -1 }
    ],
    tokenPrec: 793
});
